---
- hosts: all
  vars:
    spf13_output_file_name: spf13-script.sh
    apt_install_packages: git

  pre_tasks:
     - name: upgrade packages
       apt: update_cache=yes
       cache_valid_time: 3600
       become: true
       become_method: sudo


  roles:
      - role: gantsign.oh-my-zsh
        users:
            - username: vagrant
              oh_my_zsh:
                  theme: agnoster
                  plugins:
                      - git
                      - git-extras
                      - colorize
                      - colored-man-pages
                      - ubuntu
                      - wd
                      - gnu-utils
                      - nmap
                      - npm
                      - nvm
                      - python
                      - rsync
                      - systemadmin
a                     - terminator
                      - common-aliases
                      - zsh-syntax-highlighting

      - role: mjanser.powerline
        powerline_users:
            -vagrant
        become: true
        become_method: sudo

      - role: angstwad.docker_ubuntu
        docker_group_members: vagrant
        become: true
        become_method: sudo



  tasks:
      - name: add cmake repo
        apt_repository: repo='ppa:george-edison55/cmake-3.x' state=present
        become: true
        become_method: sudo

      - name: add ubuntu testing repos
        apt_repository: repo='ppa:ubuntu-toolchain-r/test' state=present
        become: true
        become_method: sudo

      - name: update apt cache
        apt: update_cache=yes
        become: true
        become_method: sudo

      - name: install bareflank deps
        apt: name={{item}} state=present
        become: true
        become_method: sudo
        with_items:
            - software-properties-common
            - python-software-properties
            - apt-transport-https
            - ca-certificates
            - cmake
            - ninja-build
            - build-essential
            - linux-headers-generic
            - libgmp-dev
            - libmpc-dev
            - libmpfr-dev
            - flex
            - bison
            - nasm
            - texinfo
            - libssl-dev
            - libxml2-dev
            - libpcre3-dev
            - libtool
            - automake
            - autotools-dev
            - zlibc
            - autoconf
            - libssl-ocaml-dev
            - ocaml
            - ocaml-source
            - ocaml-libs

      - name: install usability packages
        apt: name={{item}} state=present
        become: true
        become_method: sudo
        with_items:
            - vim
            - curl
            - wget
            - git
            - zsh

      - name: Dist-upgrade
        apt: 
            update_cache: yes
            upgrade: dist
        become: true
        become_method: sudo


      #- name: Download spf13 vim install script
        #get_url: url=http://j.mp/spf13-vim3 dest=~/{{ spf13_output_file_name }}
        #run_once: true
        #become: true
        #become_user: vagrant

      #- name: launch spf13 install script
        #command: sh ~/{{ spf13_output_file_name }}
        #run_once: true
        #become: true
        #become_user: vagrant

      - name: clone multi compiler project
        git: repo=git@github.com:/ilovepi/hypervisor-super.git
                dest=~/project
                version=master
                depth=1
                accept_hostkey=true
                recursive=yes
                update=yes
                track_submodules=yes
        become: true
        become_user: vagrant


      - name: patch printf.h
        replace: dest=~/project/printf.h regexp='__wur __THROW' replace='__THROW __wur' backup=yes
        #replace: dest=/usr/include/printf.h regexp='__wur __THROW' replace='__THROW __wur' backup=yes



      #- name: clone multi compiler project
        #git: repo=git@github.com:/securesystemslab/multicompiler-priv.git
                #dest=~/compilers/llvm
                #version=cfar_38
                #depth=1
                #accept_hostkey=true
        #become: true
        #become_user: vagrant

      #- name: Clone Multi Compiler Clang
        #git: repo=git@github.com:/securesystemslab/multicompiler-clang-priv.git
                #dest=~/compilers/llvm/tools/clang
                #version=cfar_38
                #depth=1
                #accept_hostkey=true
        #become: true
        #become_user: vagrant

      #- name: Clone Multi Compiler Compiler-RT
        #git: repo=git@github.com:/securesystemslab/multicompiler-compiler-rt-priv.git
                #dest=~/compilers/llvm/projects/compiler-rt
                #version=cfar_38
                #depth=1
                #accept_hostkey=true
        #become: true
        #become_user: vagrant

      #- name: Clone Multi Compiler PoolAlloc
        #git: repo=git@github.com:/securesystemslab/poolalloc
                #dest=~/compilers/llvm/projects/poolalloc
                #version=cfar_38
                #depth=1
                #accept_hostkey=true
        #become: true
        #become_user: vagrant

      #- name: Clone Multi Compiler SVF
        #git: repo=git@github.com:/rboggild/SVF
                #dest=~/compilers/llvm/projects/svf
                #depth=1
                #accept_hostkey=true
        #become: true
        #become_user: vagrant

      #- name: Clone Gold Linker
        #git: repo=git@github.com:/securesystemslab/binutils.git
                #dest=~/compilers/binutils
                #depth=1
                #version=random_commons-2_24
                #accept_hostkey=true
                #update=no
        #become: true
        #become_user: vagrant

      #- name: Create compiler/tools directory
        #file: path=~/compilers/tools state=directory
        #become: true
        #become_user: vagrant

  #post_tasks:
    #- script: cleanup.sh
      #become: true
